title: Genome Gamers
description: "Pilot City Project: A platform for gamers to share their experiences and connect with others."
owner_name: Pradyun Gowda
github_username: Prad-coder
github_repo: "GenomeGamersFrontend" 
baseurl: "/GenomeGamersFrontend"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/Search.md